blank_issues_enabled: true
contact_links:
- name: Start here / ask a question
  url: https://github.com/CONNECT-EAGLE/testrepo/blob/main/COMMUNITY.md
  about: Find the right pathway for help, contribution, and collaboration.
